### ISSUE TITLE
On Complete handler not always respected for logged in when bypass modal is enabled

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-free-downloads#211]
Scenario:
1) Logged In User
2) Bypass Modal for logged in enabled
3) On-Complete Handler: Purchase confirmation

When using this scenario, the files just auto-download, without redirecting to the purchase confirmation.

I've confirmed this is a bug on `master` as well as `release/2.2.0` and is not directly fixed in #152, as it's not the same scope.

**Comment by cklosowski** [comment]
This might have been fixed in #152.

**Comment by dannyb195** [comment]
testing against current status of branch issue/152-v2 this is still an issue... current settings:

<img width="508" alt="screen shot 2017-10-24 at 10 33 56 am" src="https://user-images.githubusercontent.com/247887/31952714-e183b2b8-b8a6-11e7-8c59-4a1fcb9f6fab.png">

**Comment by cklosowski** [comment]
Just confirmed this is fixed in the `release/2.2.0` branch. Logged in user, auto complete handler is "Purchase Confirmation" and bypass when logged in sent me to the purchase confirmation.
