### ISSUE TITLE
Optional name setting = Required Name

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-free-downloads#54]
If you uncheck the Require Name setting, it still requires the name:

<img width="632" alt="screen shot 2016-04-11 at 4 38 00 pm" src="https://cloud.githubusercontent.com/assets/1638128/14441747/431f4166-0004-11e6-9650-b46f7ed0c18f.png">

<img width="387" alt="screen shot 2016-04-11 at 4 39 28 pm" src="https://cloud.githubusercontent.com/assets/1638128/14441750/446991b6-0004-11e6-8efd-38040816a456.png">

**Comment by pippinsplugins** [comment]
@ghost1227 could we get this looked at please?

**Comment by pippinsplugins** [comment]
This isn't working for me. I can still submit the form without entering my first or last name. Note: I'm doing this while logged in.

**Comment by ghost1227** [comment]
@pippinsplugins  You're reading it backwards.... with the require name setting unchecked, it SHOULD let you submit without entering first/last name.

**Comment by pippinsplugins** [comment]
@ghost1227 Setting says `Should we make the first and last name fields required?`. That means it should be required. Fields show an aseterik but the fields can be left empty still, even if the `Should we make the first and last name fields required?` option is checked.

**Comment by ghost1227** [comment]
@pippinsplugins So I fixed it too well and reversed the problem.. Ok

**Comment by ghost1227** [comment]
Fixed

**Comment by pippinsplugins** [comment]
Nope, still not working for me.

I can still submit the form without ever seeing an error:

![screen shot 2016-04-25 at 12 01 15 pm](https://cloud.githubusercontent.com/assets/1034109/14795453/73567528-0add-11e6-8342-7335fa5e0813.png)

**Comment by pippinsplugins** [comment]
Nope, still doesn't work.

**Comment by pippinsplugins** [comment]
Nvm, working.
