### ISSUE TITLE
Add setting to make modal registration form fields optional (not required)

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-free-downloads#93]
If the registration form fields are not going to honor EDD's Guest Checkout setting, the registration form fields should at least have the ability to be optional. A checkbox setting would suffice.

**Comment by ghost1227** [comment]
Note to myself... this is specifically referencing the first and last name fields. Email is ALWAYS required unless Direct Download is enabled.

**Comment by ghost1227** [comment]
@SDavisMedia I just tested it, and with registration enabled, only username and email are required... am I missing something?

**Comment by ghost1227** [comment]
I'm punting this to 2.2.0 because I'm not convinced it's an issue and 2.1.0 has to go out ASAP due to a critical bug in variable pricing.

**Comment by SDavisMedia** [comment]
This is _not_ about first and last name fields... and certainly not email. It's about registration form fields as mentioned: https://cl.ly/2o1Z3S361h2F 

Just because we have the ability to show a registration form should not imply that registration is required. Just like with EDD itself, you can show an _optional_ registration form at checkout. The same could/should be possible in Free Downloads. 

We've actually discussed this in Slack already. You talked about adding a setting near this setting: https://cl.ly/2e0K0u0T1B1w A setting for whether or not the registration form fields are required, as mentioned in the issue title.

Does that clear this up a bit? @ghost1227

**Comment by ghost1227** [comment]
Oh! Yea, I completely misunderstood. I thought you were saying if registration was enabled, it was requiring the first and last name fields. Totally got you now.

**Comment by ghost1227** [comment]
I _think_ we fixed this with 2.0.0, but let's double check it.

**Comment by cklosowski** [comment]
This is still an issue, here is my modal while logged out:
![screen shot 2017-10-17 at 10 51 58 am](https://user-images.githubusercontent.com/1390124/31680477-43818fea-b329-11e7-9a24-7686315c20e4.png)

And my EDD setting showing that I allow guest checkout:
![screen shot 2017-10-17 at 10 52 32 am](https://user-images.githubusercontent.com/1390124/31680496-56525604-b329-11e7-8125-6bf1c0a8881a.png)

**Comment by dannyb195** [comment]
The option and modal output has been added here https://github.com/easydigitaldownloads/edd-free-downloads/compare/release/2.2.0...issue/93?expand=1 though the logic for bypassing the fields is not yet done as this work is dependent on the #206 PR which is a rather large rewrite of the modal itself

**Comment by cklosowski** [comment]
I would actually say this should respect the results of `edd_no_guest_checkout()`. I want to do this outside of #152, once that's merged in.

**Comment by cklosowski** [comment]
By following the EDD setting, we reduce the need for another setting in FD that is hidden by JS.

**Comment by dannyb195** [comment]
PR at https://github.com/easydigitaldownloads/edd-free-downloads/pull/219

**Comment by cklosowski** [comment]
Ready for testing @easydigitaldownloads/core-devs 

This allows you to show the registration fields, and it respects the edd setting to disable guest checkout.

**Comment by pippinsplugins** [comment]
This is working great for me, merging.
